 //Método consumido desde el menú
 ### get juegos por usuario 
GET http://localhost:3500/api/juegos-usuario?idUsr=123



// Se consume cuando se carga un juego 
### get juego
GET  http://localhost:3500/api/juego?idUsr=123&idJuego=sagrario-altar



//Se consume al final de cada juego o cuando se pasa de un nivel a otro en un juego
### Actualizar avance de juego
PUT  http://localhost:3500/api/juego?idUsr=123&idJuego=sagrario-altar
Content-Type: application/json

{    
    "avance" : 0,
    "terminado": false
}




// ***********************************************************************************
//Activa o desactiva el juego Endpoint para pruebas solamente
### Update estado de activo del juego
PUT http://localhost:3500/api/toggle-juego?idUsr=123&idJuego=sagrario-altar
Content-Type: application/json

{
    "activo": true
}


