
### get objetos por usuario
GET http://localhost:3500/api/objetos-usuario?idUsr=123

### Actualizar objeto
PUT http://localhost:3500/api/objetos-usuario?idUsr=123
Content-Type: application/json

{
    "idObjeto": "2",       
    "activo" : false,
    "visto" : false  
}